Update geometry_utils.py
Shapely 2.0 introduces breaking change to its multi-part geometries that cause the following exception: 

  File "/usr/local/lib/python3.11/dist-packages/movingpandas/geometry_utils.py", line 150, in mrr_diagonal
    if len(geom) == 2:
       ^^^^^^^^^
TypeError: object of type 'MultiPoint' has no len() 

More details can be found at: https://shapely.readthedocs.io/en/stable/migration.html